'''
Mappings of fields for routine filling of various Workbench fields based on files and Workbench upload type

TO ADD: what is currently in the csv _headers files of valid, downfilling, required fields
but need to decide on new field names first

list of field names, as dictionary?
    fieldname, dict tuples?

this replaces:
Create_Fillable: WB_field_model_extensions
Filled_to_WB: ModelToResourceType, ModelToDisplayHints
'''
# directories and files
FILESTOUPLOAD_DIR = "files_to_upload"
METADATA_DIR = "metadata"
CV_DIR = "_CVs"
FIELDS_DIR = "fields"
AS_AGENTS_FILENAME = "agents_in_AS.csv"
ISO639_FILENAME = "iso639.csv"
RELATOR_CODES_FILENAME = "relator.csv"

# prefixes
file_SINGLE_PREFIX = '/mnt/ingest/data/'
url_alias_PREFIX = '/islandora/object/'

# ArchivesSpace fields
# these aren't necessary i think
WB_from_AS_multi_mappings = {
    'field_description_long': ('scopecontent', 'abstract'),
    'field_note': ('odd','bioghist','accruals','dimensions','altformavail','phystech','physdesc','processinfo','separatedmaterial')
}

WB_from_AS_direct_mappings = {
    'component_id': 'field_local_identifier',
    'field_related_materials_note': 'note/relatedmaterial/0/content',
    'title': 'title',
}

# Workbench fields
WB_end_direct_mappings = {
    'title': 'field_metadata_title',
}

WB_downfilling = (
    'field_member_of',
    'field_collection2',
    'field_parent_collection_call_num',
    'field_collection_url',
)


# TO ADD: something along the lines of "keep even if blank in output"
# or just fields that are required to exist in output
WB_fields = (
        {
        'field_name': 'file',
        'description': 'File or folder name. Autogenerated from files.',
        'required_in_template_SINGLE': True,
        'required_in_template_BOOK': True,
        'downfilling': False,
    },
    {
        'field_name': 'total_scans',
        'description': 'Number of scans. Autogenerated from files.',
        'required_in_template_SINGLE': False,
        'required_in_template_BOOK': True,
        'downfilling': False,
    },
)

WB_FIELDS_ALL = (
    'file',
    'total_scans',
    'field_resource_type',
    'field_model',
    'field_member_of',
    'title',
    'field_metadata_title',
    'id',
    'parent_id',
    'field_weight',
    'field_display_hints',
    'field_alternative_title',
    'field_subtitle',
    'field_linked_agent',
    'field_speaker_affiliation',
    'field_family',
    'field_description_long',
    'field_conference',
    'field_table_of_contents',
    'field_note',
    'field_biographical_note',
    'field_genre',
    'field_physical_form',
    'field_edtf_date_created',
    'field_date_created_text',
    'field_subject',
    'field_cnair_subject',
    'field_local_subject',
    'field_subject_olac',
    'field_subjects_name',
    'field_geographic_subject',
    'field_coordinates',
    'field_temporal_subject',
    'field_language',
    'field_olac_discourse_type',
    'field_olac_linguistic_type',
    'field_place2',
    'field_publisher',
    'field_extent',
    'field_legacy_identifier',
    'field_original_format',
    'field_digital_origin',
    'field_reformatting_quality',
    'field_legacy_model',
    'field_date_digitized',
    'field_date_modified',
    'field_recording_number',
    'field_program_number',
    'field_legacy_type',
    'field_classification',
    'field_edition',
    'field_collection2',
    'field_parent_collection_call_num',
    'field_collection_url',
    'field_restrictions_on_access',
    'field_mods_relateditem_titleinfo',
    'field_related_materials_note',
    'field_related_resource_url',
    'field_access_restricted',
    'field_mods_subject_displaylabel',
    'field_administrative_notes',
    'field_access_terms',
    'TEI',
    'url_alias',
    'field_local_identifier'
)


#WB_FIELDS_ALL = [] # make this a list from the dictionary

# Workbench field defaults - ones with _BOOK are for book only
field_digital_origin = 'Reformatted digital'
field_model_BOOK = 'Paged Content'
field_resource_type_BOOK = 'Collection'
field_display_hints_BOOK = ''
field_weight = ''
parent_id = ''

# File extensions to Workbench values
# This is fairly repetitive as field_display_hints and mimetype are based on specific extensions, while generally
# field_access_terms, field_model and field_resource_type are grouped
extension_to_WB_field = (
    {
        'extension': '.wav',
        'field_access_terms': 'Restricted Audio',
        'field_display_hints': None,
        'field_model': 'Audio',
        'field_resource_type': 'Sound',
        'mimetype': None
    },
    {
        'extension': '.mp3',
        'field_access_terms': 'Restricted Audio',
        'field_display_hints': None,
        'field_model': 'Audio',
        'field_resource_type': 'Sound',
        'mimetype': 'DUMMY MP3 MIMETYPE'
    },
    {
        'extension': '.pdf',
        'field_access_terms': None,
        'field_display_hints': 'PDFjs',
        'field_model': 'Digital Document',
        'field_resource_type': 'Collection',
        'mimetype': None
    },
    {
        'extension': '.tif',
        'field_model': 'Image',
        'field_access_terms': None,
        'field_display_hints': 'Open Seadragon',
        'field_resource_type': 'Still Image',
        'mimetype': None
    },
    {
        'extension': '.jpg',
        'field_model': 'Image',
        'field_access_terms': None,
        'field_display_hints': 'Open Seadragon',
        'field_resource_type': 'Still Image',
        'mimetype': 'DUMMY JPG MIMETYPE'
    },
    {
        'extension': '.jp2',
        'field_model': 'Image',
        'field_access_terms': None,
        'field_display_hints': 'Open Seadragon',
        'field_resource_type': 'Still Image',
        'mimetype': 'DUMMY JP2 MIMETYPE'
    },
    {
        'extension': '.mp4',
        'field_model': 'Video',
        'field_access_terms': None,
        'field_display_hints': None,
        'field_resource_type': 'Moving Image',
        'mimetype': None
    },
    {
        'extension': '.mov',
        'field_model': 'Video',
        'field_access_terms': None,
        'field_display_hints': None,
        'field_resource_type': 'Moving Image',
        'mimetype': None
    },
    {
        'extension': '.mts',
        'field_model': 'Video',
        'field_access_terms': None,
        'field_display_hints': None,
        'field_resource_type': 'Moving Image',
        'mimetype': None
    }
)

EXTENSIONS = [x['extension'] for x in extension_to_WB_field]

# from Filled_to_WB.py

'''
mappings -
field_model to field_resource_type transformation
field_model to field_display_hints transformation
both could go in _ConvertData.py

FORMERLY: ModelToResourceType
FORMERLY: ModelToDisplayHints
'''
field_model_to_field_resource_type = {
    'Collection': 'Collection',
    'Audio': 'Sound',
    'Image': 'Still Image',
    'Page': 'Text',
    'Paged Content': 'Collection',
    'Digital Document': 'Collection',
    'Video': 'Moving Image'
    }

# Digital Document is interpreted from Create_Fillable as PDF
# Image can be produced from a jpg or a tif. if it's a problem to use Open Seadragon for jpg, change this.
field_model_to_field_display_hints = {
    'Digital Document': 'PDFjs',
    'Image': 'Open Seadragon'
}

# new!
field_model_to_field_access_terms = {
    'Audio': 'Restricted Audio'
}