'''
Mappings of fields for routine filling of various Workbench fields based on files and Workbench upload type

TO ADD: what is currently in the csv _headers files of valid, downfilling, required fields
but need to decide on new field names first

list of field names, as dictionary?
    fieldname, dict tuples?

this replaces:
Create_Fillable: WB_field_model_extensions
Filled_to_WB: ModelToResourceType, ModelToDisplayHints
'''
# directories and files
FILESTOUPLOAD_DIR = "files_to_upload"
METADATA_DIR = "metadata"
CV_DIR = "_CVs"
FIELDS_DIR = "fields"
AS_AGENTS_FILENAME = "agents_in_AS.csv"
ISO639_FILENAME = "iso639.csv"
RELATOR_CODES_FILENAME = "relator.csv"

# prefixes
file_SINGLE_PREFIX = '/mnt/ingest/data/'
url_alias_PREFIX = '/islandora/object/'

# other
VALIDATE_ERROR_PREFIX = "!! ERROR - "
BOOK_TITLE_URL_ALIAS_LENGTH = 92

# Workbench

WB_FIELDS_REQUIRED_AT_INPUT_SINGLE = (
    'file',
    'field_resource_type',
    'field_model',
    'field_member_of',
    'title',
    'field_digital_origin',
    'field_parent_collection_call_num',
    'field_collection2',
    'field_collection_url',
    'field_reformatting_quality',
)

WB_FIELDS_REQUIRED_AT_INPUT_BOOK = (
    'file',
    'field_resource_type',
    'field_model',
    'field_member_of',
    'title',
    'field_digital_origin',
    'field_parent_collection_call_num',
    'field_collection2',
    'field_collection_url',
    'field_reformatting_quality',
    'total_scans'
)

WB_FIELDS_DOWNFILLING = (
    'field_member_of',
    'field_collection2',
    'field_parent_collection_call_num',
    'field_collection_url',
)

WB_FIELDS_EXPORT_KEEP_EMPTY_SINGLE = (
    'field_member_of',
    'parent_id'
)

WB_FIELDS_EXPORT_KEEP_EMPTY_BOOK = (
    'field_member_of',
    'parent_id',
    'field_weight',
    'field_display_hints'
)

WB_field_linked_agent_SPLIT_FIELDS = (
    'field_linked_agent_NAME',
    'field_linked_agent_ROLE',
    'field_linked_agent_TYPE'
)

'''
field name, description tuples
These are used to:
1. display helpful descriptions on the Fillable sheet
2. rearrange the output fields to CDS's preferred order
Not every field benefits from a description, or even needs one (those that are autofilled at the end, for instance)
'''
WB_FIELDS_ORDERED_WITH_DESCRIPTION = (
    ('file','Name of file/folder. Autogenerated'),
    ('total_scans','Number of scans in a book. Autogenerated'),
    ('field_resource_type','Autogenerated'),
    ('field_model','Autogenerated'),
    ('field_member_of','Existing collection node to place object under. LEAVE BLANK if creating new nodes. Fills down.'),
    ('title','Title of object'),
    ('field_metadata_title',''),
    ('id',''),
    ('parent_id',''),
    ('field_weight',''),
    ('field_display_hints',''),
    ('field_alternative_title',''),
    ('field_subtitle',''),
    ('field_linked_agent',''),
    ('field_linked_agent_NAME','Name part of linked agent. Pipe-separate.'),
    ('field_linked_agent_ROLE','Role (relator code) part of linked agent. Pipe-separate, one for each of NAME'),
    ('field_linked_agent_TYPE','Type part of linked agent. Leave blank if all are type \'person\'. Otherwise pipe-separate abbreviations (p|c|f) or full (person|corporate_body|family), one for each NAME'),
    ('field_speaker_affiliation',''),
    ('field_family',''),
    ('field_description_long','Scope and Contents-style description'),
    ('field_conference',''),
    ('field_table_of_contents',''),
    ('field_note','Additional note'),
    ('field_biographical_note',''),
    ('field_genre',''),
    ('field_physical_form',''),
    ('field_edtf_date_created','EDTF form of date (either this or text)'),
    ('field_date_created_text','Text form of date (either this or EDTF)'),
    ('field_subject',''),
    ('field_cnair_subject',''),
    ('field_local_subject',''),
    ('field_subject_olac',''),
    ('field_subjects_name',''),
    ('field_geographic_subject',''),
    ('field_coordinates',''),
    ('field_temporal_subject',''),
    ('field_language','ISO639 language names and codes. Enter either.'),
    ('field_olac_discourse_type',''),
    ('field_olac_linguistic_type',''),
    ('field_place2',''),
    ('field_publisher',''),
    ('field_place_published',''),
    ('field_extent',''),
    ('field_legacy_identifier',''),
    ('field_original_format',''),
    ('field_digital_origin','Value assumed. Change if incorrect.'),
    ('field_reformatting_quality',''),
    ('field_legacy_model',''),
    ('field_date_digitized','Date digitized, estimated from file metadata. Change if you know this to be wrong.'),
    ('field_date_modified',''),
    ('field_recording_number',''),
    ('field_program_number',''),
    ('field_legacy_type',''),
    ('field_classification',''),
    ('field_edition',''),
    ('field_collection2','Collection title, e.g. John Tukey Papers. Fills down.'),
    ('field_parent_collection_call_num','Collection call number e.g. Mss.Ms.Coll.42. Fills down.'),
    ('field_collection_url','Collection URL, e.g. https://as.amphilsoc.org/repositories/2/resources/3085. Fills down.'),
    ('field_restrictions_on_access',''),
    ('field_mods_relateditem_titleinfo',''),
    ('field_related_materials_note',''),
    ('field_related_resource_url',''),
    ('field_related_object','DigLib node to relate to this object.'),
    ('field_access_restricted',''),
    ('field_mods_subject_displaylabel',''),
    ('field_administrative_notes','Internal (non-public) note'),
    ('field_access_terms',''),
    ('TEI',''),
    ('url_alias','An alternate URL, for long/repeated titles. Prefix will be filled.'),
    ('field_local_identifier','')
)


WB_FIELDS_ALL = [x[0] for x in WB_FIELDS_ORDERED_WITH_DESCRIPTION]


# Workbench field defaults - ones with _BOOK are for book only
field_digital_origin = 'Reformatted digital'
field_model_BOOK = 'Paged Content'
field_resource_type_BOOK = 'Collection'
'''
unnecessary - superseded by WB_FIELDS_EXPORT_KEEP_EMPTY
field_display_hints_BOOK = ''
field_weight = ''
parent_id = ''
'''


# File extensions to Workbench values
# This is fairly repetitive as field_display_hints and mimetype are based on specific extensions, while generally
# field_access_terms, field_model and field_resource_type are grouped
extension_to_WB_field = (
    {
        'extension': '.wav',
        'field_access_terms': 'Restricted Audio',
        'field_display_hints': None,
        'field_model': 'Audio',
        'field_resource_type': 'Sound',
        'mimetype': None
    },
    {
        'extension': '.mp3',
        'field_access_terms': 'Restricted Audio',
        'field_display_hints': None,
        'field_model': 'Audio',
        'field_resource_type': 'Sound',
        'mimetype': 'DUMMY MP3 MIMETYPE'
    },
    {
        'extension': '.pdf',
        'field_access_terms': None,
        'field_display_hints': 'PDFjs',
        'field_model': 'Digital Document',
        'field_resource_type': 'Collection',
        'mimetype': None
    },
    {
        'extension': '.tif',
        'field_model': 'Image',
        'field_access_terms': None,
        'field_display_hints': 'Open Seadragon',
        'field_resource_type': 'Still Image',
        'mimetype': None
    },
    {
        'extension': '.jpg',
        'field_model': 'Image',
        'field_access_terms': None,
        'field_display_hints': 'Open Seadragon',
        'field_resource_type': 'Still Image',
        'mimetype': 'DUMMY JPG MIMETYPE'
    },
    {
        'extension': '.jp2',
        'field_model': 'Image',
        'field_access_terms': None,
        'field_display_hints': 'Open Seadragon',
        'field_resource_type': 'Still Image',
        'mimetype': 'DUMMY JP2 MIMETYPE'
    },
    {
        'extension': '.mp4',
        'field_model': 'Video',
        'field_access_terms': None,
        'field_display_hints': None,
        'field_resource_type': 'Moving Image',
        'mimetype': None
    },
    {
        'extension': '.mov',
        'field_model': 'Video',
        'field_access_terms': None,
        'field_display_hints': None,
        'field_resource_type': 'Moving Image',
        'mimetype': None
    },
    {
        'extension': '.mts',
        'field_model': 'Video',
        'field_access_terms': None,
        'field_display_hints': None,
        'field_resource_type': 'Moving Image',
        'mimetype': None
    }
)

EXTENSIONS = [x['extension'] for x in extension_to_WB_field]

# check to validate that all Workbench fields referenced are in WB_FIELDS_ALL
def _Workbench_fields_consistency_check():
    for x in (
        WB_FIELDS_REQUIRED_AT_INPUT_SINGLE,
        WB_FIELDS_REQUIRED_AT_INPUT_BOOK,
        WB_FIELDS_DOWNFILLING,
        WB_FIELDS_EXPORT_KEEP_EMPTY_SINGLE,
        WB_FIELDS_EXPORT_KEEP_EMPTY_BOOK
        ):
        for y in x:
            if y not in WB_FIELDS_ALL:
                raise ValueError("Workbench fields error: this field is referenced in one WB_FIELDS tuple but not WB_FIELDS_ALL: " + str(y))
            
_Workbench_fields_consistency_check()