'''
validates some of the filled fields prior to Workbench transformation
this is not as rigorous as Workbench's validations, but is good for catching some likely errors
any erroneous data generated by the Workbench output from these scripts should be flagged with Paul Sutherland/CDS

REVISED - TEST after skipping second row on import
'''

import os
import pandas
from argparse import ArgumentParser
import _Constants_and_Mappings as c
import _ExtractDir, _Validate

INPUT_FIELDS_DIR = "_INPUT_FIELDS"

'''
Parse command line arguments
required, positional: source file
'''
print('Checking command line arguments - expected: [input spreadsheet]')

cl_parser = ArgumentParser()
cl_parser.add_argument('input_file', type=str)
cl_args = cl_parser.parse_args()

# assign arguments
INPUT_FILENAME = cl_args.input_file
if INPUT_FILENAME not in _ExtractDir.file_list(c.METADATA_DIR, extensions=True):
    raise OSError("Folder " + c.METADATA_DIR + " does not appear to contain " + INPUT_FILENAME + ". Check.")

print("... command line arguments okay.")
'''
Load input file xlsx to Pandas DataFrame then make it a dict for ease of access
'''
# import as type str so doesn't make dates
input_pd_dataframe = pandas.read_excel(os.path.join(c.METADATA_DIR, INPUT_FILENAME), dtype=str)
input_dict = input_pd_dataframe.to_dict(orient='list')
# find out how many records we have. this is stored in shape.
# TO DO - SKIP SECOND ROW ON IMPORT
INPUT_ROW_COUNT = input_pd_dataframe.shape[0]
# store fields to a tuple
INPUT_FIELDS = tuple(input_dict.keys())

'''
Basic fields check. Check that all fields are valid.
'''

print("Checking fields ...")
for f in INPUT_FIELDS:
    if f not in c.WB_FIELDS_ALL:
        # exception for the split field_linked_agent fields
        if f not in c.WB_field_linked_agent_SPLIT_FIELDS:
            raise ValueError("Input spreadsheet has an invalid field: " + str(f))

print("... all fields are valid fields.")

'''
Validation for a few fields
'''

print("Validating some fields ...")

# field_linked_agent fields

if 'field_linked_agent_NAME' and 'field_linked_agent_ROLE' and 'field_linked_agent_TYPE' in INPUT_FIELDS:
    print("Checking field_linked_agent fields ...")

    print("... checking role codes ...")
    for x in input_dict["field_linked_agent_ROLE"]:
        if not _Validate.nan(x):
            # multiple options possible. split:
            for y in x.split('|'):
                try:
                    _Validate.relator_code(y)
                except Exception as e:
                    print(c.VALIDATE_ERROR_PREFIX + str(e))

    print("... checking that name and role are same lengths ...")
    for i in range(INPUT_ROW_COUNT):
        if not _Validate.nan(input_dict["field_linked_agent_NAME"][i]):
            try:
                _Validate.piped_fields_same_length(input_dict["field_linked_agent_NAME"][i], input_dict["field_linked_agent_ROLE"][i])
            except Exception as e:
                print(c.VALIDATE_ERROR_PREFIX + str(e))

    print("... checking that type is always empty or same length as name ...")
    for i in range(INPUT_ROW_COUNT):
        if not _Validate.nan(input_dict["field_linked_agent_TYPE"][i]):
            try:
                _Validate.piped_fields_same_length(input_dict["field_linked_agent_NAME"][i], input_dict["field_linked_agent_TYPE"][i])
            except Exception as e:
                print(c.VALIDATE_ERROR_PREFIX + str(e))

    print("... checking type ...")
    for i in range(INPUT_ROW_COUNT):
        ts = input_dict["field_linked_agent_TYPE"][i]
        if not _Validate.nan(ts):
            for t in ts.split('|'):
                try:
                    _Validate.agent_type(t)
                except Exception as e:
                    print(c.VALIDATE_ERROR_PREFIX + str(e))

    print("Checked field_linked_agent.")

# field_edtf_date_created

if "field_edtf_date_created" in INPUT_FIELDS:
    print("Checking field_edtf_date_created for valid EDTF dates ...")
    for x in input_dict["field_edtf_date_created"]:
        if not _Validate.nan(x):
            # multiple options possible. split: (NEWLY ADDED)
            for y in x.split('|'):
                try:
                    _Validate.EDTF(y)
                except Exception as e:
                    print(c.VALIDATE_ERROR_PREFIX + str(e))

# field_cnair_subject

if "field_cnair_subject" in INPUT_FIELDS:
    print("Checking field_cnair_subject...")
    for x in input_dict["field_cnair_subject"]:
        if not _Validate.nan(x):
            # multiple options possible. split:
            for y in x.split('|'):
                try:
                    _Validate.CNAIR_culture(y)
                except Exception as e:
                    print(c.VALIDATE_ERROR_PREFIX + str(e))

# field_language

if "field_language" in INPUT_FIELDS:
    print("Checking field_language...")
    for x in input_dict["field_language"]:
        if not _Validate.nan(x):
            # multiple options possible. split:
            for y in x.split('|'):
                try:
                    _Validate.ISO639_code(y)
                except Exception as e:
                    print(c.VALIDATE_ERROR_PREFIX + str(e))

# title

if "title" in INPUT_FIELDS:
    print("Checking that all titles are unique...")
    # uses set() to remove duplicate values
    titles = input_dict["title"]
    if len(titles) != len(set(titles)):
        print("!! Warning - one or more titles are not unique, which will cause redirect errors. Ensure use of url_alias.")
    print("Checking lengths of titles...")
    for title in titles:
        if len(title) >= c.BOOK_TITLE_URL_ALIAS_LENGTH:
            print("!! Warning - if a Book, the following title needs a url_alias under " + str(c.BOOK_TITLE_URL_ALIAS_LENGTH) + " characters:" + str(title))

print("Validation of the above fields complete. This does not catch many fields. Resolve any errors noted above.")