'''
For converting the json file of ISO639 codes (generated by LBeaudoux) into a CSV, for use as a controlled value
the latest version is here: https://github.com/LBeaudoux/iso639/blob/bb15c9fc5abfd094b3ebedee3c8f9a2bc628cfb9/iso639/data/iso-639.json
this assumes that all codes are pt3 or pt5, which is true as of 2024, and only handles 3-digit codes. 

This could be improved to use argparse
'''

# ARGUMENTS: filepath for the json

import sys
import json
import utilities.use_CSVs as use_CSVs

filepath = sys.argv[1]

# get the json file

file = open(filepath)
all_dict = json.load(file)
file.close()

# get just the names dict
names_dict = all_dict["name"]

# construct tuple list of ISO639 names and codes
ISO639 = []
# get ISO639-3:
for k, v in names_dict.items():
    if v["pt3"]:
        ISO639.append((k, v["pt3"]))
    if v["pt5"]:
        ISO639.append((k, v["pt5"]))

if len(ISO639) == len(names_dict.items()):
    # export to csv using my CSV utility
    use_CSVs.tuples_to_CSV(ISO639, "iso639.csv")
else:
    print("It looks like there are some languages that are not exclusively ISO639-3 or ISO639-5, so are not caught by this process. investigate.")