'''
File defining constants, Workbench fields, and mappings between different fields
'''
from aspace_wb.utils import use_CSVs
from importlib.resources import files as import_file
from aspace_wb.data import vocabularies

'''
Locations of files & directories; controlled vocabularies; misc
'''


# directories and files
FILESTOUPLOAD_DIR = "files_to_upload"
METADATA_DIR = "metadata"
CV_DIR = "vocabularies" # controlled vocabularies
FIELDS_DIR = "fields"
AS_AGENTS_FILENAME = "agents_in_AS.csv"
ISO639_FILENAME = "iso639.csv"
CNAIR_SUBJECTS_FILENAME = "cnair_subject.csv"
RELATOR_CODES_FILENAME = "relator.csv"

# controlled vocabularies, from the above
LANGUAGE_NAMES = use_CSVs.CSV_col_to_list(import_file(vocabularies).joinpath(ISO639_FILENAME), 0)
LANGUAGE_CODES = use_CSVs.CSV_col_to_list(import_file(vocabularies).joinpath(ISO639_FILENAME), 1)
CNAIR_SUBJECTS = use_CSVs.CSV_col_to_list(import_file(vocabularies).joinpath(CNAIR_SUBJECTS_FILENAME), 0)
# CNAIR_SUBJECTS = use_CSVs.CSV_col_to_list(os.path.join(CV_DIR, CNAIR_SUBJECTS_FILENAME), 0)
RELATOR_CODES = use_CSVs.CSV_col_to_list(import_file(vocabularies).joinpath(RELATOR_CODES_FILENAME), 0)
# RELATOR_CODES = use_CSVs.CSV_col_to_list(os.path.join(CV_DIR, RELATOR_CODES_FILENAME), 0)

# other
VALIDATE_ERROR_PREFIX = "!! ERROR - "
AS_DIGITAL_OBJECT_NODE_PREFIX = "islandora8_"
AS_DIGITAL_OBJECT_FILE_URI_PREFIX = "https://diglib.amphilsoc.org/node/"
BOOK_TITLE_URL_ALIAS_LENGTH = 92

'''
Workbench fields

'''

# field defaults - ones with _BOOK are for book only
field_digital_origin = 'Reformatted digital'
field_reformatting_quality = 'Preservation'
field_model_BOOK = 'Paged Content'
field_resource_type_BOOK = 'Collection'

# field text prefixes (referencing locations within the upload server)
file_SINGLE_PREFIX = '/mnt/ingest/data/'
url_alias_PREFIX = '/islandora/object/'

# required fields that must exist in a "fields" csv BEFORE running create_fillable.py
WB_FIELDS_REQUIRED_AT_INPUT_SINGLE = (
    'file',
    'field_resource_type',
    'field_model',
    'field_member_of',
    'title',
    'field_digital_origin',
    'field_parent_collection_call_num',
    'field_collection2',
    'field_collection_url',
    'field_reformatting_quality',
)

WB_FIELDS_REQUIRED_AT_INPUT_BOOK = (
    'file',
    'field_resource_type',
    'field_model',
    'field_member_of',
    'title',
    'field_digital_origin',
    'field_parent_collection_call_num',
    'field_collection2',
    'field_collection_url',
    'field_reformatting_quality',
    'total_scans'
)

# fields that will fill downwards through gaps
WB_FIELDS_DOWNFILLING = (
    'field_member_of',
    'field_collection2',
    'field_parent_collection_call_num',
    'field_collection_url',
)

# fields required after filled_to_wb.py to exist, even if/necessarily empty
WB_FIELDS_EXPORT_KEEP_EMPTY_SINGLE = (
    'field_member_of',
    'parent_id'
)

WB_FIELDS_EXPORT_KEEP_EMPTY_BOOK = (
    'field_member_of',
    'parent_id',
    'field_weight',
    'field_display_hints'
)

# fields that field_linked_agent gets split into and reformed from
# this is only called once out of several places it could be called (in which individual field names are typed out)
WB_field_linked_agent_SPLIT_FIELDS = (
    'field_linked_agent_NAME',
    'field_linked_agent_RELATOR',
    'field_linked_agent_TYPE'
)

# field names and their descriptions, as tuples
# 1. these display to the user in the Fillable sheet (not every field needs one or will display in that sheet)
# 2. the order here is the order that the Workbench csv will output

WB_FIELDS_ORDERED_WITH_DESCRIPTION = (
    ('file','Name of file/folder. Autogenerated'),
    ('total_scans','Number of scans in a book. Autogenerated'),
    ('field_resource_type','Autogenerated'),
    ('field_model','Autogenerated'),
    ('field_member_of','Existing collection node to place object under. LEAVE BLANK if creating new nodes. Fills down.'),
    ('title','Title of object'),
    ('field_metadata_title',''),
    ('id',''),
    ('parent_id',''),
    ('field_weight',''),
    ('field_display_hints',''),
    ('field_alternative_title',''),
    ('field_subtitle',''),
    ('field_linked_agent',''),
    ('field_linked_agent_NAME','Name, written as in Library of Congress subject headings. If multiple values, separate with pipes'),
    ('field_linked_agent_RELATOR','Relator codes for the names given in field_linked_agent_NAME. Must input one for each name, pipe-separated'),
    ('field_linked_agent_TYPE',"Can be person, corporate_body, or family. Abbreviations acceptable (p, c, or f). Include one for each name in field_linked_agent_NAME, pipe-separated, OR leave blank if all are of type 'person'"),
    ('field_speaker_affiliation',''),
    ('field_family',''),
    ('field_description_long','Scope and Contents-style description'),
    ('field_conference',''),
    ('field_table_of_contents',''),
    ('field_note','Additional note, e.g. caveats about scanning or metadata quality'),
    ('field_biographical_note',''),
    ('field_genre',''),
    ('field_physical_form',''),
    ('field_edtf_date_created',"Date in EDTF format (enter either here or in field_date_created_text; don't enter in both)"),
    ('field_date_created_text',"Date as freeform text (enter either here or infield_edtf_date_created; don't enter in both)"),
    ('field_subject',''),
    ('field_cnair_subject','Controlled vocabulary: consult vocabularies/cnair_subject.csv, Airtable, or Indigenous Subject Guide'),
    ('field_local_subject',''),
    ('field_subject_olac','Legacy CNAIR only. Not for new materials.'),
    ('field_subjects_name',''),
    ('field_geographic_subject','Consult Library of Congress'),
    ('field_coordinates',''),
    ('field_temporal_subject',''),
    ('field_language','Enter an ISO639 language name OR code'),
    ('field_olac_discourse_type',''),
    ('field_olac_linguistic_type',''),
    ('field_place2',''),
    ('field_publisher',''),
    ('field_place_published',''),
    ('field_extent','Autogenerated if possible. Recount manually if scans include blank pages.'),
    ('field_legacy_identifier',''),
    ('field_original_format','See https://diglib.amphilsoc.org/taxonomy/vocab/original_format/all (first letter capitalized only)'),
    ('field_digital_origin','Value assumed. Change if incorrect.'),
    ('field_reformatting_quality','Value assumed. Change if incorrect.'),
    ('field_legacy_model',''),
    ('field_date_digitized','Date digitized, estimated from file metadata. Change if you know this to be wrong.'),
    ('field_date_modified',''),
    ('field_recording_number','Legacy audio only. Use field_local_identifier for new audio.'),
    ('field_program_number','Legacy audio only. Use field_local_identifier for new audio.'),
    ('field_legacy_type',''),
    ('field_classification',''),
    ('field_edition',''),
    ('field_collection2','Collection title, e.g. John Tukey Papers. Fills down.'),
    ('field_parent_collection_call_num','Collection call number e.g. Mss.Ms.Coll.42. Fills down.'),
    ('field_collection_url','ArchivesSpace collection URL, e.g. https://as.amphilsoc.org/repositories/2/resources/3085. Fills down.'),
    ('field_restrictions_on_access',''),
    ('field_mods_relateditem_titleinfo','Collection title to relate to this object'),
    ('field_related_materials_note','Note on related collection'),
    ('field_related_resource_url','Collection URL to relate to this object'),
    ('field_related_object','DigLib node to relate to this object'),
    ('field_access_restricted',''),
    ('field_mods_subject_displaylabel',''),
    ('field_administrative_notes','Internal (non-public) note'),
    ('field_access_terms','Uploading restricted items is not yet worked out. Autogenerated for audio.'),
    ('TEI',''),
    ('url_alias','An alternate URL, for long/repeated titles. Prefix will be filled.'),
    ('field_local_identifier','Equivalent to Component Unique Identifier. Use for alternate (non-title/chrono) arrangement in a collection.'),
    ('field_internet_media_type','Media Type, a file format identification standard. Autogenerated')
)

# all the above fields as a list, for simpler access
WB_FIELDS_ALL = [x[0] for x in WB_FIELDS_ORDERED_WITH_DESCRIPTION]

# File extensions to Workbench values
# This is fairly repetitive as field_display_hints and field_internet_media_type are based on specific extensions
# for field_internet_media_type standard consult https://www.iana.org/assignments/media-types/media-types.xhtml and/or https://mimetype.io 
#  (for some reason these are distinct. wav is not included in IANA.)
# field_access_terms, field_model and field_resource_type always come in a group
extension_to_WB_field = (
    {
        'extension': '.wav',
        'field_access_terms': 'Restricted Audio',
        'field_display_hints': None,
        'field_model': 'Audio',
        'field_resource_type': 'Sound',
        'field_internet_media_type': 'audio/wav' # https://mimetype.io/audio/vnd.wav official but apparently less supported than audio/wav, see discussion on linked github page
    },
    {
        'extension': '.mp3',
        'field_access_terms': 'Restricted Audio',
        'field_display_hints': None,
        'field_model': 'Audio',
        'field_resource_type': 'Sound',
        'field_internet_media_type': 'audio/mpeg'
    },
    {
        'extension': '.pdf',
        'field_access_terms': None,
        'field_display_hints': 'PDFjs',
        'field_model': 'Digital Document',
        'field_resource_type': 'Collection',
        'field_internet_media_type': 'application/pdf'
    },
    {
        'extension': '.tif',
        'field_model': 'Image',
        'field_access_terms': None,
        'field_display_hints': 'Open Seadragon',
        'field_resource_type': 'Still Image',
        'field_internet_media_type': 'image/tiff'
    },
    {
        'extension': '.jpg',
        'field_model': 'Image',
        'field_access_terms': None,
        'field_display_hints': 'Open Seadragon',
        'field_resource_type': 'Still Image',
        'field_internet_media_type': 'image/jpeg'
    },
    {
        'extension': '.jp2',
        'field_model': 'Image',
        'field_access_terms': None,
        'field_display_hints': 'Open Seadragon',
        'field_resource_type': 'Still Image',
        'field_internet_media_type': 'image/jp2'
    },
    {
        'extension': '.mp4',
        'field_model': 'Video',
        'field_access_terms': None,
        'field_display_hints': None,
        'field_resource_type': 'Moving Image',
        'field_internet_media_type': 'video/mp4'
    },
    {
        'extension': '.mov',
        'field_model': 'Video',
        'field_access_terms': None,
        'field_display_hints': None,
        'field_resource_type': 'Moving Image',
        'field_internet_media_type': 'video/quicktime'
    },
    {
        'extension': '.mts',
        'field_model': 'Video',
        'field_access_terms': None,
        'field_display_hints': None,
        'field_resource_type': 'Moving Image',
        'field_internet_media_type': 'video/MP2T'
    }
)

# list of extensions, for simple access
EXTENSIONS = [x['extension'] for x in extension_to_WB_field]

'''
Check that runs on any use, to validate that all Workbench fields referenced are in WB_FIELDS_ALL
this will flag an error if we update the fields but forget something
'''
def _WB_fields_consistency_check():
    for x in (
        WB_FIELDS_REQUIRED_AT_INPUT_SINGLE,
        WB_FIELDS_REQUIRED_AT_INPUT_BOOK,
        WB_FIELDS_DOWNFILLING,
        WB_FIELDS_EXPORT_KEEP_EMPTY_SINGLE,
        WB_FIELDS_EXPORT_KEEP_EMPTY_BOOK
        ):
        for y in x:
            if y not in WB_FIELDS_ALL:
                raise ValueError("Workbench fields error: this field is referenced in one WB_FIELDS tuple but not WB_FIELDS_ALL: " + str(y))
            
_WB_fields_consistency_check()