'''
Validates some of the filled fields prior to Workbench transformation
This is not as rigorous as Workbench's validations, but is good for catching some likely errors
Any erroneous data generated by the Workbench output from these scripts should be flagged with CDS/Paul Sutherland

TO ADD? validate that DOWNFILLING are valid. warn if empty.
... which is a variation of this from earlier version of Filled_to_WB:

    for header in headers_required:
        if header in headers_downfilling:
            # raise error if the first value in a downfilling column is not present
            if not input_dict[header][0]:
                raise ValueError("Input spreadsheet needs to have at least the first row filled in column: " + header)
        else:
            # raise error if any of the rows are empty
            if "" in input_dict[header]:
                raise ValueError("Column " + header + " in input spreadsheet needs to be completely filled.")
'''

import os
import pandas
from argparse import ArgumentParser
from aspace_wb.utils import default_specs as c
from aspace_wb.utils import extract_dir, validate, convert_data

'''
Parse command line arguments
    required, positional: Workbench upload type (single/book)
    required, positional: filled file
'''

cl_parser = ArgumentParser()
cl_parser.add_argument('type', type=str, choices=('single', 'book'), help="Workbench upload type: 'book' (an object with multiple pages) or 'single' (a graphic, audio, or video object)")
cl_parser.add_argument('filled_file', type=str, help="Name (with .xlsx extension) of your simplified Workbench sheet")
cl_parser.add_argument('--skiploc', action='store_true', help="Skip validation of LOC headings. Use if you've already run LOC validation and want wb-validate to run faster")
cl_args = cl_parser.parse_args()

# assign arguments

# WB_type from type
WB_type = cl_args.type

# FILLED_FILENAME from filled_file
FILLED_FILENAME = cl_args.filled_file
if FILLED_FILENAME not in extract_dir.file_list(c.METADATA_DIR, extensions=True):
    raise OSError(f"Workbench sheet {FILLED_FILENAME} not found in folder {c.METADATA_DIR}. Check file name and location and try again.")

# skip_loc from --skip-loc
skip_loc = cl_args.skiploc

'''
Load input file xlsx to Pandas DataFrame then make it a dict for ease of access

on loading input file we:
import as type str so it doesn't try to make dates
skip row index 1 to ignore descriptions
'''

print("Loading filled file ...")
# load input file:
# import as type str so doesn't make dates
input_pd_dataframe = pandas.read_excel(os.path.join(c.METADATA_DIR, FILLED_FILENAME), dtype=str, skiprows=[1])
input_dict = input_pd_dataframe.to_dict(orient='list')
# find out how many records we have. this is stored in shape.
INPUT_ROW_COUNT = input_pd_dataframe.shape[0]
# store fields to a tuple
INPUT_FIELDS = tuple(input_dict.keys())

'''
Basic fields check. Check that all fields are valid.
'''

print("Checking fields ...")
for f in INPUT_FIELDS:
    if f not in c.WB_FIELDS_ALL:
        # exception for the split field_linked_agent fields
        if f not in c.WB_field_linked_agent_SPLIT_FIELDS:
            raise ValueError("Input spreadsheet has an invalid field: " + str(f))

if WB_type == 'single':
    for f in c.WB_FIELDS_REQUIRED_AT_INPUT_SINGLE:
        if f not in INPUT_FIELDS:
            raise ValueError("Input spreadsheet missing necessary field: " + str(f))
elif WB_type == 'book':
    for f in c.WB_FIELDS_REQUIRED_AT_INPUT_BOOK:
        if f not in INPUT_FIELDS:
            raise ValueError("Input spreadsheet missing necessary field: " + str(f))


print("... all fields are valid fields.")

'''
Validation for a few fields
'''

print("Validating some fields ...")

# title
# first checks that it's not empty

if "title" in INPUT_FIELDS:
    titles = input_dict["title"]
    if validate.list_is_all_empty(titles):
        print(c.VALIDATE_ERROR_PREFIX + "Titles appear to be empty")
    else:
        print("Checking that all titles are unique...")
        # uses set() to remove duplicate values
        if len(titles) != len(set(titles)):
            print("!! Warning - one or more titles are not unique, which will cause redirect errors. Ensure use of url_alias.")
        print("Checking lengths of titles...")
        for title in titles:
            if len(title) >= c.BOOK_TITLE_URL_ALIAS_LENGTH:
                print(f"!! Warning - if a Book, the following title needs a url_alias under {str(c.BOOK_TITLE_URL_ALIAS_LENGTH)} characters: {str(title)}")

# check that entries in field_linked_agent_NAME, field_subject, field_subjects_name, field_geographic_subject, and field_temporal_subject are valid LOC and print a warning if not

if not skip_loc:
    print("... validating LOC subject headings ...")

    # add all checked LOC to a dict to avoid checking again
    # separate by authority to increase chance of catching errors where an LOC appears in wrong column (e.g. a name in field_subject)
    loc_dict = {
        "names": {},
        "subjects": {},
        "other": {}
    }

    if "field_linked_agent_NAME" in INPUT_FIELDS:
        validate.check_subject_fields(
            input_dict["field_linked_agent_NAME"], 
            "names", 
            loc_dict)

    if "field_subject" in INPUT_FIELDS:
        validate.check_subject_fields(
            input_dict["field_subject"], 
            "subjects", 
            loc_dict)
    if "field_subjects_name" in INPUT_FIELDS:
        validate.check_subject_fields(
            input_dict["field_subjects_name"], 
            "names", 
            loc_dict)
    #TODO: should these search a specific authority? may need to add functionality to loc-api
    if "field_geographic_subject" in INPUT_FIELDS:
        validate.check_subject_fields(
            input_dict["field_geographic_subject"], 
            None, 
            loc_dict)
    if "field_temporal_subject" in INPUT_FIELDS:
        validate.check_subject_fields(
            input_dict["field_temporal_subject"], 
            None, 
            loc_dict)
        
    # print(loc_dict)


# field_linked_agent fields

if 'field_linked_agent_NAME' in INPUT_FIELDS and 'field_linked_agent_RELATOR' in INPUT_FIELDS and 'field_linked_agent_TYPE' in INPUT_FIELDS: #swap for a reference to c
    print("Checking field_linked_agent fields ...")

    print("... checking relator codes ...")
    # TO DO? could we allow title entry of relators too?
    for relators in input_dict["field_linked_agent_RELATOR"]:
        if not validate.nan(relators):
            # multiple options possible. split:
            for relator in relators.split('|'):
                try:
                    validate.relator_code(relator)
                except Exception as e:
                    print(c.VALIDATE_ERROR_PREFIX + str(e))

    print("... checking that name and relator are same lengths ...")
    for i in range(INPUT_ROW_COUNT):
        if not validate.nan(input_dict["field_linked_agent_NAME"][i]):
            try:
                validate.piped_fields_same_length(input_dict["field_linked_agent_NAME"][i], input_dict["field_linked_agent_RELATOR"][i])
            except Exception as e:
                print(c.VALIDATE_ERROR_PREFIX + str(e))

    print("... checking that type is always empty or same length as name ...")
    for i in range(INPUT_ROW_COUNT):
        if not validate.nan(input_dict["field_linked_agent_TYPE"][i]):
            try:
                validate.piped_fields_same_length(input_dict["field_linked_agent_NAME"][i], input_dict["field_linked_agent_TYPE"][i])
            except Exception as e:
                print(c.VALIDATE_ERROR_PREFIX + str(e))

    print("... checking type ...")
    for i in range(INPUT_ROW_COUNT):
        types = input_dict["field_linked_agent_TYPE"][i]
        if not validate.nan(types):
            for t in types.split('|'):
                try:
                    validate.agent_type(t)
                except Exception as e:
                    print(c.VALIDATE_ERROR_PREFIX + str(e))

    print("Checked field_linked_agent.")

# field_edtf_date_created

if "field_edtf_date_created" in INPUT_FIELDS:
    print("Checking field_edtf_date_created for valid EDTF dates ...")
    for x in input_dict["field_edtf_date_created"]:
        if not validate.nan(x):
            # multiple options possible. split: (NEWLY ADDED)
            for y in x.split('|'):
                try:
                    validate.EDTF(y)
                except Exception as e:
                    print(c.VALIDATE_ERROR_PREFIX + str(e))

# field_cnair_subject

if "field_cnair_subject" in INPUT_FIELDS:
    print("Checking field_cnair_subject...")
    for x in input_dict["field_cnair_subject"]:
        if not validate.nan(x):
            # multiple options possible. split:
            for y in x.split('|'):
                try:
                    validate.CNAIR_culture(y)
                except Exception as e:
                    print(c.VALIDATE_ERROR_PREFIX + str(e))

# field_language
if "field_language" in INPUT_FIELDS:
    print("Checking field_language...")
    for value in input_dict["field_language"]:
        if not validate.nan(value):
            languages = value.split("|")
            for language in languages:
                try:
                    lang_code = convert_data.lang_info_to_wb(language)
                except Exception as e:
                    print(c.VALIDATE_ERROR_PREFIX + str(e))


print("Validation of the above fields complete. This does not catch many fields. Resolve any errors noted above.")